#Data Source Properties
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/books?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: 123321
  #JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: TRUE
    hibernate:
      ddl-auto: update
    open-in-view: false
  ###
  mvc:
    hiddenmethod:
      filter:
        enabled: true
###Logging Levels
# Disable the default loggers
logging:
  level:
    org: WARN
    blog: WARN
    #Show SQL executed with parameter bindings
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor: TRACE

#Change server port
#server.port: 8000
